### ISSUE TITLE
Offset not working 

### ISSUE THREAD

**Issue by harrygeier** [Spritkopf/freecad-macros#1]
If you OFFSET the clipping plane,the macro will still clip at the original position of the clipping plane

![2018-04-30 12_15_42-freecad](https://user-images.githubusercontent.com/38854839/39423046-613afcca-4c70-11e8-9139-891c25b71e0e.png)

I would be nice if that can be added

**Comment by Spritkopf** [comment]
You are right... I pushed a fix which now creates the plane at the base-position of the plane, not at the origin.

Thanks
