### ISSUE TITLE
Integrate `clip_sketch` into https://github.com/FreeCAD/FreeCAD-macros/

### ISSUE THREAD

**Issue by galou** [Spritkopf/freecad-macros#2]
Thank for this macro!

Please integrate into https://github.com/FreeCAD/FreeCAD-macros/:
- Add an icon
- Change the name to start with `Sketcher` (I would suggest `SketcherClipView.FCMacro`).
- Put the macro in either the directory `PureGui` or `Sketcher`.
- Add the metadata as stated below.

Metadata:
__Name__ = ''
__Comment__ = ''
__Web__ = ''
__Wiki__ = ''
__Icon__ = ''
__Help__ = ''
__Author__ = ''
__Version__ = ''
__Status__ = ''
__Requires__ = 'FreeCAD >= v0.17'

**Comment by Spritkopf** [comment]
I am honored :)

I created the pull request
